### ISSUE TITLE
Review atelier 1

### ISSUE THREAD

**Issue by Stephanethr** [Cleamx/L3#3]
# dans le constructeur il y a un paramètre nom qui n'est pas envoyé au constructeur de la classe mère.
https://github.com/Cleamx/L3/blob/9b6fb7565ce7e51888b94a46024d1a2f3c4aac7e/javaAtelier/Atelier1/exercice1/src/DesMemoire.java#L7-L9

**Comment by Stephanethr** [comment]
# idem que l'issue précédente, le nom du paramètre n'est pas utilisé

https://github.com/Cleamx/L3/blob/9b6fb7565ce7e51888b94a46024d1a2f3c4aac7e/javaAtelier/Atelier1/exercice1/src/DesPipes.java#L7-L12

**Comment by Stephanethr** [comment]
# La méthode setBorneMin est définie en private, or les accesseurs doivent être définies en public pour être accessible depuis les autres classes
https://github.com/Cleamx/L3/blob/9b6fb7565ce7e51888b94a46024d1a2f3c4aac7e/javaAtelier/Atelier1/exercice1/src/DesPipes.java#L31-L39

**Comment by Stephanethr** [comment]
# incremente
https://github.com/Cleamx/L3/blob/9b6fb7565ce7e51888b94a46024d1a2f3c4aac7e/javaAtelier/Atelier1/exercice2/entier.java#L43-L48
Ici tu peux rendre plus générique la méthode incremente en initialisant un n = 1, et faire la même vérification que dans la fonction surchargée (si ta valeur est égale a 3 et ton max a 4 tu incrémentes mais après ça ta valeur sera égale au max) :
https://github.com/Cleamx/L3/blob/9b6fb7565ce7e51888b94a46024d1a2f3c4aac7e/javaAtelier/Atelier1/exercice2/entier.java#L58-L58

**Comment by Stephanethr** [comment]
# L'incrémentation de l'entier fou dois être entre 0 et le niveau de folie, ici le minimum sera toujours 1

https://github.com/Cleamx/L3/blob/aa81af262c775d72062d7c3741a29dac3f641d03/javaAtelier/Atelier1/exercice2/entierFou.java#L26-L29

**Comment by Cleamx** [comment]
c'est fait mec
